# Generated by Django 5.2 on 2025-05-10 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_has_consented'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='has_consented',
        ),
    ]
