# Generated by Django 5.2 on 2025-05-08 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_alter_duration_end_time_alter_duration_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='duration',
            name='duration_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
