# Generated by Django 5.2 on 2025-05-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duration',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='duration',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
