# Generated by Django 5.2 on 2025-05-05 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_notification_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
