# Generated by Django 5.2 on 2025-05-10 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_consented',
            field=models.BooleanField(default=False),
        ),
    ]
